name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup latest CMake
      uses: lukka/get-cmake@latest

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake (x64 Release)
      run: cmake --preset x64-release

    - name: Build (x64 Release)
      run: cmake --build --preset x64-release

    - name: Test
      run: ctest --preset x64-release

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe-debug
        path: out/build/x64-debug/*.exe